stages:
- build  

build_job:
stage: build
only:
- branches
script:
- 'cd ConsoleApp2'
- '"D:\Nuget\nuget.exe" restore'
- '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" ConsoleApp1.sln'
artifacts:
paths:
- 'ConsoleApp1\bin\Debug\netcoreapp3.1\ConsoleApp1.exe'
